### ISSUE TITLE
New substitution suggestions?

### ISSUE THREAD

**Issue by warpling** [warpling/Macmoji#1]
If you want to submit some ideas/suggestions please keep it tidy and use a table like this:

| replace | with |
| :-- | --- |
| laughing | 😄 |
| silly | 😜 |

Just copy past this template to get started. (Make sure you have a newline before the table!)

```

| replace | with |
| :------- | ------- |
| laughing | 😄 |
| silly | 😜 |
```

**Comment by alexlafroscia** [comment]
You might want to put that in a [Github issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) instead!

**Comment by warpling** [comment]
Thanks @alexlafroscia! Didn't know I could do that :D I'm on it.
