### ISSUE TITLE
Emoji Query 😎

### ISSUE THREAD

**Issue by lfarah** [warpling/Macmoji#10]
I'd be cool to add an emoji query just like _Github_ does:
<img width="218" alt="screen shot 2016-07-11 at 12 33 29 am" src="https://cloud.githubusercontent.com/assets/6511079/16719309/36525684-46ff-11e6-99a7-7ee7f11b8a3f.png">
Yeah, for this to work, **Macmoji** would have to be an actual program. Maybe a Chrome Extension?

**Comment by kurisubrooks** [comment]
Could easily make this into an Electron app that runs in the background. 
I think there are a couple that already do this, though..

**Comment by warpling** [comment]
Totally. Macmoji was only meant to be a very simple stopgap.
I just heard about the [Mojito](mojito.cool) project, which is pretty close to this!

**Comment by lfarah** [comment]
Makes sense....
