### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by jcampbell05** [warpling/Macmoji#12]
We have to figure how to make this work on iOS :D

**Comment by warpling** [comment]
iOS 10 [adds something pretty similar](http://www.apple.com/ios/ios10-preview/)!
My shortcuts automatically synced to my phone but typing with the colons is kind of a pain. On top of that it appears there's a bug (at least in iOS 10) that causes the substitutions to enter the autocorrect dictionary too so I'm getting suggestions to correct `peach` with `:peach:`.
