### ISSUE TITLE
iMessage Sync Ports Text Replacement to iPhone, Converts Basic Words

### ISSUE THREAD

**Issue by satnam** [warpling/Macmoji#15]
After copying the .plist file over as instructed, I noticed while on my iPhone, typing basic words like "zzz" will result in text replacement with the emoji. I checked Settings -> Keyboards -> Text Replacement and I see the plist entries there as they are denoted with colons. However, the colons appear to be ignored in iMessage and Mail, so even if you just type the word "zzz" or "airplane" the text will be replaced with the emoji.

**Comment by ssbozy** [comment]
I kinda like that in a way.  Just try typing trump and see what happens 👍

**Comment by warpling** [comment]
Sorry for the slow reply @satnam. You're totally right, the text substitutions are syncing via iCloud. I can't find a way to stop the syncing and have added this to the FAQ, but the only solution I know at the moment is to remove the substitutions :(

**Comment by warpling** [comment]
Filed radar 27377015 confirming this on iOS 8/9.

**Comment by marcusrbrown** [comment]
Turn off Auto Correction under General -> Keyboard.

**Comment by warpling** [comment]
Doesn't that turn off spell-check corrections too?

**Comment by marcusrbrown** [comment]
Nizzope! :) On my iOS devices I still see spelling suggestions that I can tap or ignore. ~~Also, this appears to be a iPhone-only issue, on my iPad I couldn't reproduce with Auto-Correction on or off.~~ It happens on iPhone or iPad with Auto-Correction enabled, it appears only for substitutions that are only letters.

**Comment by warpling** [comment]
Good to know! It seems that's the solution for now.

**Comment by satnam** [comment]
I realize the issue is closed as a result of @igetgames's proposed solution. However, I like having auto-correct enabled and don't know if I like the trade off here, but thanks for pointing it out anyway, @igetgames @warpling.

**Comment by warpling** [comment]
I'm with your @satnam :/ I don't believe there's a better workaround available at the moment though.

Have you checked out Matthew Palmer's more native implementation?: [Rocket](http://matthewpalmer.net/rocket/)

**Comment by marcusrbrown** [comment]
@satnam It sucks, yeah, but I have to get along without auto-correct - induces too much rage over here. IMO the issue needs to be resolved in iOS.

The only other way I know of to prevent the substitutions from syncing to iCloud-enabled devices is to turn of "Documents and Data" syncing. And then you'd lose a lot more than just text substitutions.

**Comment by satnam** [comment]
@warpling I understand. I haven't looked at Rocket, but thanks for sharing! @igetgames I have come to rely on auto-correct, so it's hard to let it go! I suppose Apple has to support markdown before it would respect wrapping words in colons, but I don't expect that to happen any time soon. :weary:

**Comment by warpling** [comment]
@satnam Yeah. Let's see if the radar get's picked up. I encourage filling yourself too to dupe it :)

**Comment by satnam** [comment]
@warpling On your suggestion, I also filed a radar!
