### ISSUE TITLE
iOS weirdness

### ISSUE THREAD

**Issue by joeldrapper** [warpling/Macmoji#21]
The iOS weirdness you describe in the documentation is due to iOS' auto correct feature. I guess they must use the substitutions as a dictionary to help 'improve' the auto correct functionality.

In my experience, it only kicks in when you type a word that doesn't already exist in your auto correct dictionary. For instance, `simplesmile` doesn't exist as an English word, and I've never taught my iPhone that word either. So typing `simplesmile` causes autocorrect to suggest the 'next best thing', a substitution that matches a fuzzy search of my substitutions, for that text.

An easy way around this is to teach iOS all the non-words that you want to be able to type. You can do this for instance by typing `simplesmile` and then manually tapping `simplesmile` from the three auto correct suggestions, before pressing space.

Alternatively, you can turn off auto correct.

With this knowledge, iCloud syncing is a **feature**. I love that I can use slack-style-emoji on iOS. It makes Basecamp and emails a lot more fun.

**Comment by warpling** [comment]
I see what you're saying, but from what I've seen in the latest iOS 10 beta, typing any of these trigger words without the colon will not cause their substitutions to fuzzy-match and show up in the substitutions drawer. Maybe things are changing? ¯_(ツ)_/¯
