### ISSUE TITLE
Add GitHub to the description

### ISSUE THREAD

**Issue by matheuss** [warpling/Macmoji#23]
Proposal: change the descripton from `Slack emoji for your mac! 😁 💥 💻` to `Slack/GitHub emoji for your mac! 😁 💥 💻` 😊

**Comment by warpling** [comment]
Is this for SEO reasons? :P I though Slack was the more well known of the two but I think I'd be down to add this.

**Comment by appleguy19** [comment]
Trello also uses the same colon style notation. Might as well get all the search traffic you can...

**Comment by warpling** [comment]
✅
