### ISSUE TITLE
Unicode 9.0 emoji

### ISSUE THREAD

**Issue by nick-f** [warpling/Macmoji#30]
With today's public release of iOS 10.2, Apple has implemented support for Unicode 9.0 emoji.

[iOS 10.2 emoji changelog](http://blog.emojipedia.org/ios-10-2-emoji-changelog/)

They're already in the macOS 10.2.2 beta, so it's only a matter of time before they're released and ready to go.

(Hopefully I will get time to do it myself, but opening this issue so if someone wants to take it upon themselves they can.)

**Comment by Korgun** [comment]
10.12.2 final was released this morning too 🍎

**Comment by warpling** [comment]
Thank you Nick! That would be fantastic. 👨🏻‍🎤

**Comment by camlloyd** [comment]
See #41!

**Comment by warpling** [comment]
Cam is the man. 🍻
