### ISSUE TITLE
realpath: command not found

### ISSUE THREAD

**Issue by matsilva** [warpling/Macmoji#35]
Using the install script command on macOS Sierra version 10.12.3 (16D32)

![image](https://cloud.githubusercontent.com/assets/4511972/23807981/eaa6d7ea-0595-11e7-9e67-d11df7d6c924.png)

I was able to fix by installing coreutils via homebrew `brew install coreutils`

**Comment by warpling** [comment]
Strange… Just curious: do you have Xcode and command line tools installed?

**Comment by matsilva** [comment]
I think so? 
here is the output of `xcode-select -v`: `xcode-select version 2347.`

**Comment by matsilva** [comment]
Anything else I should run to help out here?

**Comment by warpling** [comment]
Sorry I lost track of this @matsilva! I don't have a clean machine to test this on but will add something to the README in the time being!

**Comment by matsilva** [comment]
@warpling no worries. Wasn't really a crisis.

**Comment by warpling** [comment]
Emojis are always a crisis, Mat. 🚨

**Comment by marwahaha** [comment]
Happened to me :(
