### ISSUE TITLE
Alfred snippet generation

### ISSUE THREAD

**Issue by valrus** [warpling/Macmoji#36]
I looked at #14 and I don't think `update-km.py` will work for Alfred snippets. The problem is that even with the template functionality, that script assumes a single output file, whereas Alfred snippet "files" are actually zipped directories containing one JSON file per snippet.

I'm game to write a second script to generate the Alfred files if you'd like. Let me know if you're interested and I'll try to have a pull request within the week.

**Comment by valrus** [comment]
Oh, heck. I just noticed you have an open pull request relevant to this already: #16. But I also notice it's unresolved. I can pick up where it left off, maybe?

**Comment by warpling** [comment]
Hey @valrus! That would be fantastic!
Please reach out if you get blocked by anything :)

**Comment by warpling** [comment]
Closing so we can keep the conversation at #16.
