### ISSUE TITLE
10.13 Support

### ISSUE THREAD

**Issue by dbuskariol** [warpling/Macmoji#39]
Although not throwing any errors, it doesn't appear that the shell script works anymore. I guess something changed with where/how macOS stores this data since the last update. Any chance we could get some compatibility with macOS High Sierra?

**Comment by warpling** [comment]
So sorry for missing this. Just tested it myself and it works on Mojave. I know it's been half a year and then some but if you get a chance to try it or experience the error please comment re-open!
