### ISSUE TITLE
Tag stable 1.0 release

### ISSUE THREAD

**Issue by bval** [warpling/Macmoji#50]
👋 I'd like to make Macmoji installable/uninstallable via Homebrew and they have a strong preference for software that has tagged stable releases. I would like to ask @warpling to tag a 1.0 release that GitHub can provide as a download, and to tag future releases as changes are made, preferably using [semantic versioning](https://semver.org).

**Comment by warpling** [comment]
Hey @bval! What else would you expect from a Homebrew install? I would think you'd also expect the install script to run or something no?

**Comment by bval** [comment]
@warpling I would. I was working on that bit and was going to see if Homebrew would allow me to run it on install, and if not at least output a message telling the user to execute `macmoji install` after putting it in the PATH.

I got sidetracked after hacking on this a bit last week but I still have issues with #52 to figure out. The install script succeeds but they don't actually show up in the Keyboard prefpane if you have iCloud syncing turned on for Text Replacement.

**Comment by warpling** [comment]
Closing for now due to removal of install script
