### ISSUE TITLE
Print: Entry, ":0:shortcut", Does Not Exist

### ISSUE THREAD

**Issue by Tealk** [warpling/Macmoji#55]
Hi,

i get the same error that has been mentioned here before:
https://github.com/warpling/Macmoji/pull/26#issuecomment-251603791

```
Macmoji-master % ./scripts/macmoji install
./scripts/macmoji: line 8: realpath: command not found
Installing Macmoji text replacements...
Print: Entry, ":0:shortcut", Does Not Exist
```

**Comment by warpling** [comment]
Hi @Tealk, I've removed the install script since I wasn't able to find a way to get it working again with the changes in the last new macOS versions. Sorry about this. Hope you were able to install it okay with the drag/drop method :)
