### ISSUE TITLE
How to add custom emoji

### ISSUE THREAD

**Issue by edvardasast** [warpling/Macmoji#57]
Hi,

Thank you for your great work, I would like to ask you if it is possible to add my custom emoji i.e. from png or gif via plist file? if yes could you provide me any hints or tutorial?

**Comment by BingeCode** [comment]
That's not possible because all the plist file contains is a mapping from the emoji to the emojicode (see below).
So you can only use emojis that macos knows already.
```
  <dict>
    <key>phrase</key>
    <string>5️⃣</string>
    <key>shortcut</key>
    <string>:five:</string>
  </dict>
```

**Comment by warpling** [comment]
Thanks for explaining @BingeCode, sorry I missed replying @edvardasast
