### ISSUE TITLE
Mappings out of order

### ISSUE THREAD

**Issue by jondcallahan** [warpling/Macmoji#6]
Things get a little funky around line 5897. Baseball is mapped to the snowman, soccer to baseball, etc. https://github.com/warpling/Macmoji/blob/master/emoji%20substitutions.plist#L5897

**Comment by warpling** [comment]
Oh man, I wonder what happened… Fixing!

**Comment by warpling** [comment]
Fixed them, thank you for pointing this out!

**Comment by warpling** [comment]
It appears if you drag in the plist again it'll just add new ones so you end up with shortcuts for `:baseball:` pointing ⛄ and ⚾️. Thankfully since the list is alphabetical it isn't too hard to select all the colon clad emoji to remove them and re-add the new plist!
