### ISSUE TITLE
:+1: doesn't seem to work

### ISSUE THREAD

**Issue by clay-to-n** [warpling/Macmoji#7]
:thumbsup: (thumbsup) works fine, as does :thumbsdown: (thumbsdown) and :-1:(-1) - but on my machine, :+1: (+1) isn't working.  I even tried re-entering the :+1: (+1) text in the "Replace" field, but no luck.

Anyone else experiencing this?

**Comment by warpling** [comment]
Strange, I just tested it again and have it working in text edit on 10.11.5 (15F34) :/
What version of mac os are you running?

**Comment by saffad** [comment]
I'm also experiencing this. Tried in both Notes.app and text edit.
OS: 10.11.5 (15F34)

**Comment by warpling** [comment]
Hah… well now my `:-1:` isn't working but `:+1:` still is.

**Comment by meemster** [comment]
My :-1: isn't working either. 10.11.4

**Comment by warpling** [comment]
Sorry everyone, still haven't been able to figure out anything conclusive about this 😖
