### ISSUE TITLE
Whatsapp Web Desktop App

### ISSUE THREAD

**Issue by ghost** [warpling/Macmoji#8]
**WhatsApp Web** doesn't work with **Macmoj**i. I think that it's the same error users are experiencing with Google Chrome. No feedback, just wanted to inform. Maybe update the list with **known issues.** 

Kindest regards

**Comment by Haroenv** [comment]
That uses Electron behind the scenes, which is Chrome stripped down.

**Comment by warpling** [comment]
@Haroenv is correct: any app build using Electron won't support system automatic spell-check or substitutions :(
